### ISSUE TITLE
`No usable GPUs found` after Docker/NVidia Driver update

### ISSUE THREAD

**Issue by MentalFS** [MentalFS/docker-boinc-client#7]
A few days ago I updated Docker for Dektop (on Windows with WSL backbone) and the NVidia drivers at the same day (which is a bit unfortunate now).

Since then, no GPU is found. Running `docker run --rm -it --gpus=all nvcr.io/nvidia/k8s/cuda-sample:nbody nbody -gpu -benchmark nbody -benchmark` shows that this is not a problem with this image itself, but I want a place to gather information.

**Comment by MentalFS** [comment]
This problem seemt to be ralated to microsoft/WSL#10253 and/or docker/for-win#13870

**Comment by MentalFS** [comment]
Downgrading to [Docker Desktop 4.29.0](https://docs.docker.com/desktop/release-notes/#4290) did not help.

**Comment by prettydeep** [comment]
I had this problem as well. Using Nvidia driver 555.85 with Docker-Desktop 4.30.0 the gpu was not recognized. Changing Docker-Desktop version did nothing.

I resolved this by downgrading the Nvidia driver to [552.22](https://www.nvidia.com/download/driverResults.aspx/224154/en-us/).

**Comment by MentalFS** [comment]
Thanks, there even is a bug report at NVIDIA/nvidia-container-toolkit/issues/520. When that's closed it should work again after an update.

**Comment by Max-Sum** [comment]
> I had this problem as well. Using Nvidia driver 555.85 with Docker-Desktop 4.30.0 the gpu was not recognized. Changing Docker-Desktop version did nothing.
> 
> I resolved this by downgrading the Nvidia driver to [552.22](https://www.nvidia.com/download/driverResults.aspx/224154/en-us/).

Thanks so much! I never though it was nvidia's driver problem.
*Linus GIF floating over my head*

**Comment by kand7dev** [comment]
> Thanks, there even is a bug report at NVIDIA/nvidia-container-toolkit/issues/520. When that's closed it should work again after an update.

A new driver released yesterday on my machine. The big fix log stated that it fixes the CUDA support. Unfortunately, the issue persists on my end. Maybe Docker Desktop/WSL needs an update as well.

**Comment by MentalFS** [comment]
Yeah I'll just wait until that issue is closed. Thank you for testing that.

**Comment by tangmingxing1988** [comment]
Docker Desktop has released v4.31.0, it sees it has resolved the issue by upgrading nvidia-container-toolkit to 1.15.0. After a simple test, it has worked well with Nvidia driver 555.x

**Comment by tangmingxing1988** [comment]
As I tested, Docker Desktop v4.31.0 has fixed the problem by upgrade nvidia container toolkit to v1.15.0. Please upgrade your docker desktop if you need.

**Comment by MentalFS** [comment]
> As I tested, Docker Desktop v4.31.0 has fixed the problem by upgrade nvidia container toolkit to v1.15.0. Please upgrade your docker desktop if you need.

Did your volumes stay intact? The release notes point to docker/for-win#14118 and warn about data loss.

**Comment by tangmingxing1988** [comment]
> > As I tested, Docker Desktop v4.31.0 has fixed the problem by upgrade nvidia container toolkit to v1.15.0. Please upgrade your docker desktop if you need.
> 
> Did your volumes stay intact? The release notes point to [docker/for-win#14118](https://github.com/docker/for-win/issues/14118) and warn about data loss.

That's an issue, you can use 4.31.1 pre-release if you care. https://desktop.docker.com/win/main/amd64/153472/Docker%20Desktop%20Installer.exe

**Comment by MentalFS** [comment]
With Docker Desktop 4.31.1 and NVidia Drivers 555.99 it does indeed work again. Let's hope it stays that way.

**Comment by MentalFS** [comment]
With Docker Desktop 4.31.1 and NVidia Drivers 555.99 it does indeed work again. Let's hope it stays that way.
